  - name: write the iptables config file
    template: 
      src=/etc/ansible/playbooks/roles/common/templates/iptables_web
      dest=/etc/sysconfig/iptables
    when: ansible_nodename == "{{ item }}"
    with_items:
      - web01
      - web02
    notify:
    - restart iptables
    tags: iptables-web
  - name: ensure iptables is running (and enable it at boot)
    service: name=iptables state=started enabled=yes
